### ISSUE TITLE
Cannot install py-libversion with pip

### ISSUE THREAD

**Issue by MaxMatti** [repology/py-libversion#5]
Using archlinux, `pip 20.0.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)`

```
$ sudo pip3 --no-cache-dir install libversion
Collecting libversion
  Downloading libversion-1.2.0.tar.gz (8.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2qe209si/libversion/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2qe209si/libversion/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-2qe209si/libversion/pip-egg-info
         cwd: /tmp/pip-install-2qe209si/libversion/
    Complete output (15 lines):
    Package libversion was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libversion.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libversion', required by 'virtual:world', not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2qe209si/libversion/setup.py", line 69, in <module>
        **pkgconfig('libversion')
      File "/tmp/pip-install-2qe209si/libversion/setup.py", line 14, in pkgconfig
        for token in subprocess.check_output(['pkg-config', '--libs', '--cflags', package]).decode('utf-8').split():
      File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['pkg-config', '--libs', '--cflags', 'libversion']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by AMDmi3** [comment]
You need https://github.com/repology/libversion installed, it says that in clear text.
